### ISSUE TITLE
Path doesn't run

### ISSUE THREAD

**Issue by Bulldo344** [V3N0M-Z/RBLX-SimplePath#10]
```lua
script.Parent.MouseClick:Connect(function(player)
	local Character = player.Character
	local humanoid = Character:WaitForChild("Humanoid")
	
	local animator = humanoid:FindFirstChildOfClass("Animator")
	local animation = animator:LoadAnimation(game:GetService("ReplicatedStorage").Animations.Typing) -- oops new thing is correct me bad bad 

	local SimplePath = require( game:GetService("ReplicatedStorage").SimplePath)
	local Part = game:GetService("ReplicatedStorage").Animations.Part
	local Path = SimplePath.new(Character)



	if Debounce then 
		Debounce = true
		humanoid.WalkSpeed = 0
		humanoid.JumpHeight = 0
		Path.Visualize = true
		Path:Run(Part.Position)
		Path.Error:Connect(function(errorType)
			warn(errorType)
			Path:Run(Part.Position)
		end)
```

This is a snippet of my code, not the whole thing. No errors when run, no nothing.

**Comment by Bulldo344** [comment]
It does still Visualize though, but doesn't run and do you guys have a discord server?

**Comment by V3N0M-Z** [comment]
`Path.Run` returns either true or false. If the computation was successful, it returns true, otherwise, if pathfinding is not possible, it returns false. Add a new line: `print(Path:Run())`, and check the output to see if it returns true. More information about this method here: https://v3n0m-z.github.io/RBLX-SimplePath/api-reference/#run.

Unfortunately, as of now, there is no Discord server.
